// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import data "gin-example/app/data"
import mock "github.com/stretchr/testify/mock"

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: _a0, _a1
func (_m *UserService) CreateUser(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// User provides a mock function with given fields: _a0, _a1
func (_m *UserService) User(_a0 string, _a1 string) (*data.User, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *data.User
	if rf, ok := ret.Get(0).(func(string, string) *data.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
